##
# Plugins
require:
  - standard

##
# Defaults: standard-rb
inherit_gem:
  standard: config/base.yml

##
# All cops
AllCops:
  TargetRubyVersion: 3.2
  Include:
    - lib/*.rb
    - lib/**/*.rb
    - libexec/*
    - libexec/*/**
    - bin/*
    - test/*
  Exclude:
    - src/css/vendor/tail.css/bin/*

##
# Enabled
Style/FrozenStringLiteralComment:
  Enabled: true

##
# Disabled
Layout/ArgumentAlignment:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: false
Layout/EmptyLineBetweenDefs:
  Enabled: false
Style/TrivialAccessors:
  Enabled: false
